image: node:7.7.2

cache:
  paths:
    - node_modules/

test:
  tags:
    - docker
  services:
    - postgres:9.6.2
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ''
  script:
    - npm install
    - npm run ci
