image: node:7.7.2

cache:
  paths:
    - node_modules/

variables:
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''

test:
  tags:
    - docker
  services:
    - postgres:9.6.2
  script:
    - npm install
    - npm run ci
