language: node_js

services:
  - postgresql

env:
  - POSTGRES_USER=knorm POSTGRES_PASSWORD=knorm POSTGRES_DB=knorm

before_script:
  - psql -c 'create database knorm;' -U postgres
  - psql -c "create user knorm with password 'knorm';" -U postgres


cache:
  directories:
    - node_modules

script:
  - npm run ci
