language: node_js

services:
  - postgresql

addons:
  postgresql: "9.6"

script:
  - npm run lint
  - npm run coverage

after_success:
  - npm run coveralls
  - test $TRAVIS_BRANCH = "master" && npm run docs:build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: knorm/knorm
  keep-history: true
  target-branch: master
  on:
      branch: master
