version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: knorm

  knorm:
    build: .
    command: npm test
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
